### PR TITLE
Fix typings for IPrivateKey and IPublicKey

### PR DESCRIPTION
**Pull request by hyochan**
image

I've see missing types in `IPrivateKey` and `IPublicKey`.

### CODE REVIEW

**Comment by hyochan** [comment]
@snanovskyi Is this released? I am still facing `tsc` error in recent packages.

image

**Comment by snanovskyi** [comment]
@hyochan yes. react-native-virgil-crypto 0.60 has identifier property in both public and private keys.
The only problem right now is e3kit due to some TypeScript issues in our unit tests.

**Comment by snanovskyi** [comment]
You can follow it here - https://github.com/VirgilSecurity/virgil-e3kit-js/pull/108. I think it will be available later today.

**Comment by hyochan** [comment]
@snanovskyi Still facing this problem. I've updated packages today in [here](https://github.com/dooboolab/hackatalk-mobile/pull/126/commits/49321d43e2de3e24abaab04325bfe8c6ab57f1dc).

**Comment by xlwknx** [comment]
Hi @hyochan !
Sorry for a delay, we've just published e3kit version 2.2.1 with new `crypto-types`.
Please try it out.

**Pull request merged**
